### PR TITLE
Fix potential IDs duplicates

### PR DESCRIPTION
**Pull request by MikeSha**
Also now it is possible to set id through props

Not sure I understand why tests are failing

### CODE REVIEW

**Comment by mehdisadeghi** [comment]
Thanks for the PR. Would you mind though explaining which problem are we solving here?

**Comment by MikeSha** [comment]
Sure. I have a complex object of MathJax data, and I need to parse it
recursively. It doesn’t mater actually, but the thing is I need unique ID
for each item in the DOM.

вт, 23 черв. 2020 о 22:40 Mehdi Sadeghi <notifications@github.com> пише:

**Comment by mehdisadeghi** [comment]
Fair enough. Just add [a default id](https://github.com/mehdisadeghi/react-mathjax-preview/pull/49/files#diff-fdd787a1718e174cc3405f9a78399e21R67) and we are good to go.

**Comment by MikeSha** [comment]
> Fair enough. Just add [a default id](https://github.com/mehdisadeghi/react-mathjax-preview/pull/49/files#diff-fdd787a1718e174cc3405f9a78399e21R67) and we are good to go.

Done! Thank you!

**Comment by mehdisadeghi** [comment]
@MikeSha I think you've some syntax error or alike. btw, I fixed that initial build issue in master, so if you update your branch it should built correctly.

**Comment by MikeSha** [comment]
Finally done :) @mehdisadeghi

**Comment by mehdisadeghi** [comment]
@MikeSha see [v2.0.2](https://unpkg.com/browse/react-mathjax-preview@2.0.2/)

**Pull request merged**
